name: 'Issue Sync with Jira'
on:
  issues:
    types: [opened]

permissions:
  issues: write
  contents: read

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
      - name: Create ticket
        run: |
          curl --request POST \
            --url 'https://algolia.atlassian.net/rest/api/3/issue' \
            --user "${{ secrets.JIRA_TOKEN }}" \
            --header 'Accept: application/json' \
            --header 'Content-Type: application/json' \
            --data '{"fields":{"description":{"content":[{"content":[{"text":"${{ github.event.issue.body }}","type":"text"}],"type":"paragraph"}],"type":"doc","version":1},"issuetype":{"id":"10003"},"parent":{"key":"DI-2737"},"project":{"id":"10118"},"summary":"[APIC] ${{ github.event.issue.title }}"},"update":{}}'
